# monaspace-argon-var

[font]
size = 12

[font.bold]
family = "Monaspace Argon Var"
style = "Bold"

[font.bold_italic]
family = "Monaspace Argon Var"
style = "Bold Italic"

[font.italic]
family = "Monaspace Argon Var"
style = "Medium Italic"

[font.normal]
family = "Monaspace Argon Var"
style = "Medium"
