[general]
live_config_reload = true

import = [
  "~/.config/alacritty/colorschemes/nightfly.toml",
  "~/.config/alacritty/fonts/jetbrains-mono.toml",
]

[colors]
draw_bold_text_with_bright_colors = false

[bell]
animation = "EaseOutExpo"
duration = 10

[cursor.style]
shape = "block"

[env]
LC_TERMINAL = "alacritty"
TERM_PROGRAM = "alacritty"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[window]
blur = true
opacity = 0.90
option_as_alt = "Both"

[window.dimensions]
columns = 132
lines = 43
