vim.opt.shortmess:append({ I = true }) -- avoid flashing intro screen bugs

require('sykesm.plugins-setup')
require('sykesm.core.options')
require('sykesm.core.clipboard')
require('sykesm.core.keymaps')
require('sykesm.core.colorscheme')
require('sykesm.core.highlight')
require('sykesm.core.augroups')
require('sykesm.plugins.cmp')
require('sykesm.plugins.gitsigns')
require('sykesm.plugins.go-nvim')
require('sykesm.plugins.lsp')
require('sykesm.plugins.lualine')
require('sykesm.plugins.neo-tree')
require('sykesm.plugins.nvim-telescope')
require('sykesm.plugins.tagbar')
require('sykesm.plugins.tohtml')
require('sykesm.plugins.treesitter')
require('sykesm.plugins.vim-hashicorp-tools')
require('sykesm.plugins.vim-matchup')
require('sykesm.plugins.vim-markdown')
